name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: DeLaGuardo/setup-clojure@10.1
        with:
          cli: 1.11.1.1155
          bb: 1.0.168
      - name: Run Babashka tests
        run: bb test-bb
      - name: Run Clojure tests
        run: clojure -X:test
